/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package parcial;

import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author keiinerp
 */
public class Diseño extends javax.swing.JFrame {

    /**
     * Creates new form Diseño
     */
    public Diseño() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        identificacionText = new javax.swing.JTextField();
        nombreText = new javax.swing.JTextField();
        guardarBoton = new javax.swing.JButton();
        empleadosCombo = new javax.swing.JComboBox<>();
        tipoEmpleadoCombo = new javax.swing.JComboBox<>();
        empleadosConPrimaBoton = new javax.swing.JButton();
        empleadosSinPrimaBoton = new javax.swing.JButton();
        totalAsignadoPrimasBoton = new javax.swing.JButton();
        mayorPrimaBoton = new javax.swing.JButton();
        menorPrimaBoton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("REGISTRO DE EMPLEADOS");

        jLabel2.setText("Nombre:");

        jLabel3.setText("Identificación:");

        jLabel4.setText("Tipo de empleado:");

        identificacionText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                identificacionTextActionPerformed(evt);
            }
        });
        identificacionText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                identificacionTextKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                identificacionTextKeyTyped(evt);
            }
        });

        nombreText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreTextActionPerformed(evt);
            }
        });

        guardarBoton.setText("Guardar");
        guardarBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarBotonActionPerformed(evt);
            }
        });

        tipoEmpleadoCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECCIONE", "DOCENTE", "ADMINISTRATIVO", "CONTRATISTA", "OTRO" }));

        empleadosConPrimaBoton.setText("Empleados con prima");
        empleadosConPrimaBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empleadosConPrimaBotonActionPerformed(evt);
            }
        });

        empleadosSinPrimaBoton.setText("Empleados sin prima");
        empleadosSinPrimaBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empleadosSinPrimaBotonActionPerformed(evt);
            }
        });

        totalAsignadoPrimasBoton.setText("Total asignado por primas");
        totalAsignadoPrimasBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalAsignadoPrimasBotonActionPerformed(evt);
            }
        });

        mayorPrimaBoton.setText("Mayor");
        mayorPrimaBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mayorPrimaBotonActionPerformed(evt);
            }
        });

        menorPrimaBoton.setText("Menor");
        menorPrimaBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menorPrimaBotonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(empleadosCombo, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(identificacionText)
                                    .addComponent(nombreText)
                                    .addComponent(tipoEmpleadoCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(empleadosConPrimaBoton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(guardarBoton)
                                    .addComponent(empleadosSinPrimaBoton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(mayorPrimaBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(menorPrimaBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(totalAsignadoPrimasBoton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(0, 85, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(identificacionText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombreText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tipoEmpleadoCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(empleadosCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(empleadosConPrimaBoton)
                    .addComponent(totalAsignadoPrimasBoton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(empleadosSinPrimaBoton)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(mayorPrimaBoton)
                            .addComponent(menorPrimaBoton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(guardarBoton))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void identificacionTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_identificacionTextActionPerformed
    
        
    
    }//GEN-LAST:event_identificacionTextActionPerformed

    private void nombreTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreTextActionPerformed

    private void guardarBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarBotonActionPerformed
nombre=nombreText.getText();
identificacion=identificacionText.getText();
tipoEmpleado=(String) tipoEmpleadoCombo.getSelectedItem();
salario=(colocarSalario(tipoEmpleado));
prima=calcularPrima(tipoEmpleado,salario);
if("CONTRATISTA".equals(tipoEmpleado)){
 empleadosCombo.addItem(nombre+"   "+tipoEmpleado+"     "+salario);
}
if("DOCENTE".equals(tipoEmpleado) || "ADMINISTRATIVO".equals(tipoEmpleado) || "CONTRATISTA".equals(tipoEmpleado)){
    listaEmpleados.add(new Empleado(nombre, identificacion,tipoEmpleado,prima,salario));
    conPrima++;
}
else{
    sinPrima++;
    JOptionPane.showMessageDialog(null, "Esta persona no tiene derecho a prima");
}
conMayorPrima();
conMenorPrima();
nombreText.setText(" ");
identificacionText.setText(" ");
tipoEmpleadoCombo.setSelectedIndex(0);
    }//GEN-LAST:event_guardarBotonActionPerformed

    private void empleadosConPrimaBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empleadosConPrimaBotonActionPerformed
JOptionPane.showMessageDialog(null, "La cantidad de empleados con prima es:    "+conPrima);
    }//GEN-LAST:event_empleadosConPrimaBotonActionPerformed

    private void empleadosSinPrimaBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empleadosSinPrimaBotonActionPerformed
JOptionPane.showMessageDialog(null, "La cantidad de empleados sin prima es:    "+sinPrima);        
    }//GEN-LAST:event_empleadosSinPrimaBotonActionPerformed

    private void mayorPrimaBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mayorPrimaBotonActionPerformed
JOptionPane.showMessageDialog(null, "El empleado con mayor prima es:    "+conMayor.getNombre()+" que goza de una prima de:  "+conMayor.getSalario());
    }//GEN-LAST:event_mayorPrimaBotonActionPerformed

    private void menorPrimaBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menorPrimaBotonActionPerformed
JOptionPane.showMessageDialog(null, "El empleado con menor prima es:    "+conMenor.getNombre()+" que tiene una prima de    "+conMenor.getPrima());
    }//GEN-LAST:event_menorPrimaBotonActionPerformed

    private void totalAsignadoPrimasBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalAsignadoPrimasBotonActionPerformed
JOptionPane.showMessageDialog(null, "El total asignado por primas es:   "+totalAsignadoPrimas());
    }//GEN-LAST:event_totalAsignadoPrimasBotonActionPerformed

    private void identificacionTextKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_identificacionTextKeyTyped

    }//GEN-LAST:event_identificacionTextKeyTyped

    private void identificacionTextKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_identificacionTextKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_identificacionTextKeyPressed
public long totalAsignadoPrimas(){
    for (int i = 0; i < listaEmpleados.size(); i++) {
        totPrimas=totPrimas+listaEmpleados.get(i).getPrima();
    }
    return totPrimas;
}
public Empleado conMayorPrima(){ 
    for (int i = 0; i < listaEmpleados.size(); i++) {
        if(listaEmpleados.get(i).getPrima()>mayor){
        mayor=listaEmpleados.get(i).getPrima();
        conMayor=listaEmpleados.get(i);
    }
}
    return conMayor;
}
public Empleado conMenorPrima(){ 
    for (int i = 0; i < listaEmpleados.size(); i++) {
        if(listaEmpleados.get(i).getPrima()<menor){
        menor=listaEmpleados.get(i).getPrima();
        conMenor=listaEmpleados.get(i);
}
}
    return conMenor;
}
public long calcularPrima(String tipoEmpleado, long salario){
    long primaE=0;
    if("DOCENTE".equals(tipoEmpleado)){
        primaE=(long) (0.35*3700000);
    }
    if("ADMINISTRATIVO".equals(tipoEmpleado)){
        primaE=(long) (0.24*4000000);
    }
    if("CONTRATISTA".equals(tipoEmpleado)){
        primaE=(long) (0.12*3500000);
    }
    return primaE;
}
public long colocarSalario(String tipoEmpleado){
        long salarioE = 0;
    if("DOCENTE".equals(tipoEmpleado)){
        salarioE=3700000;
    }
    if("ADMINISTRATIVO".equals(tipoEmpleado)){
        salarioE=4000000;
    }
    if("CONTRATISTA".equals(tipoEmpleado)){
        salarioE=3500000;
    }
    return salarioE;
}
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Diseño.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Diseño.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Diseño.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Diseño.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Diseño().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> empleadosCombo;
    private javax.swing.JButton empleadosConPrimaBoton;
    private javax.swing.JButton empleadosSinPrimaBoton;
    private javax.swing.JButton guardarBoton;
    private javax.swing.JTextField identificacionText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton mayorPrimaBoton;
    private javax.swing.JButton menorPrimaBoton;
    private javax.swing.JTextField nombreText;
    private javax.swing.JComboBox<String> tipoEmpleadoCombo;
    private javax.swing.JButton totalAsignadoPrimasBoton;
    // End of variables declaration//GEN-END:variables
ArrayList<Empleado> listaEmpleados = new ArrayList<>();
public String nombre;
public String identificacion;
public long salario;
public long prima;
public String tipoEmpleado;
public long totPrimas;
public long mayor=0;
public long menor=999999999;
public int conPrima=0;
public int sinPrima=0;
public Empleado conMayor=null;
public Empleado conMenor=null;
}
